apiVersion: v1
kind: Service
metadata:
  name: archive
  namespace: appveen
spec:
  type: LoadBalancer
  selector:
    app: archive
    release: '1.0.0'
  ports:
    - protocol: TCP
      name: archive
      port: 32000
      targetPort: 8000
      nodePort: 32000
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: archive
  namespace: appveen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: archive
      release: '1.0.0'
  template:
    metadata:
      labels:
        app: archive
        release: '1.0.0'
    spec:
      serviceAccountName: odp-admin-appveen
      volumes:
      - name: docker-sock
        hostPath:
          path: /var/run
      containers:
        - name: archive
          image: 'odp-archive:1.0.0'
          ports:
            - containerPort: 8000
          securityContext:
            privileged: true
          volumeMounts:
            - name: docker-sock
              mountPath: /var/run